# Generated by Django 5.1.5 on 2025-02-03 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_testuser_alter_book_options_alter_book_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('patronymic', models.CharField(blank=True, max_length=30, null=True)),
                ('birthdate', models.DateTimeField()),
                ('deathdate', models.DateTimeField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Биография')),
            ],
        ),
        migrations.DeleteModel(
            name='TestUser',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='book.authors'),
        ),
    ]
