# Generated by Django 4.2.19 on 2025-02-27 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('book', '0004_alter_authors_options_alter_book_options_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='author.authors'),
        ),
        migrations.AlterField(
            model_name='history',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='book.book'),
        ),
        migrations.DeleteModel(
            name='Authors',
        ),
    ]
